index:
  path: /
  controller: App\Controller\Index::index
app_login:
  path: /login
  controller: App\Controller\LoginController::index
app_logout:
  path: /logout
  controller: App\Controller\LoginController::logOut
