<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container42xSzUx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container42xSzUx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container42xSzUx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container42xSzUx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container42xSzUx\App_KernelDevDebugContainer([
    'container.build_hash' => '42xSzUx',
    'container.build_id' => '75043bc2',
    'container.build_time' => 1641907490,
], __DIR__.\DIRECTORY_SEPARATOR.'Container42xSzUx');
