<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6txooju\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6txooju/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6txooju.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6txooju\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6txooju\App_KernelDevDebugContainer([
    'container.build_hash' => '6txooju',
    'container.build_id' => '5f2db1bb',
    'container.build_time' => 1642077768,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6txooju');
