<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/dashboard']], [], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileController::index'], [], [['text', '/profile']], [], [], []],
    'user_list' => [[], ['_controller' => 'App\\Controller\\UserListController::index'], [], [['text', '/users/list']], [], [], []],
    'app_add_user' => [[], ['_controller' => 'App\\Controller\\UserListController::add'], [], [['text', '/users/add']], [], [], []],
    'app_remove_user' => [['id'], ['_controller' => 'App\\Controller\\UserListController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/remove']], [], [], []],
    'app_reset_password_user' => [['id'], ['_controller' => 'App\\Controller\\UserListController::resetPassword'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users/resetpassword']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\Index::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logOut'], [], [['text', '/logout']], [], [], []],
];
